/* Affirm' — scroll-scrubbed signing hands
   Frame sequences generated with Higgsfield (Seedance 2.0, start→end frame),
   scrubbed on a <canvas> indexed by scroll progress. Song chapters follow the
   active affirmation; light/dark theme inverts the stage. */

const AFFIRMATIONS = [
  "My hands shape the life I imagine.",
  "I am fluent in my own becoming.",
  "I speak, even in silence.",
  "Every gesture moves me forward.",
  "I am the author and the alphabet.",
  "What I affirm, I become.",
  "I begin before I feel ready.",
  "My breath is proof of my becoming.",
  "I carry calm into every room.",
  "I choose the thought that carries me.",
  "Today bends toward my intention.",
  "I am allowed to take up space.",
  "My pace is a rhythm, not a race.",
  "I turn setbacks into instructions.",
  "I keep promises to myself first.",
  "My attention is my superpower.",
  "I make peace with the unfinished.",
  "I grow in the direction of my gaze.",
  "Small steps are still choreography.",
  "I trust the timing of my life.",
  "I am the calm inside the noise.",
  "My worth is not up for a vote.",
  "I water what I want to grow.",
  "Fear is a visitor, not a landlord.",
  "I answer doubt with evidence.",
  "My kindness is a form of strength.",
  "I build bridges out of my mistakes.",
  "I am both the sculptor and the clay.",
  "Rest is part of my momentum.",
  "I let go of what lets go of me.",
  "My voice matters before it is loud.",
  "I am becoming someone I admire.",
  "Gratitude sharpens my vision.",
  "I meet this moment with open hands.",
  "I am rich in second chances.",
  "My curiosity outlives my fear.",
  "I belong wherever I arrive whole.",
  "I forgive the earlier drafts of me.",
  "Joy is a discipline I practice.",
  "I hold my dreams with both hands.",
  "The light I seek, I also share.",
  "I am patient with my unfolding.",
  "My boundaries are love with edges.",
  "I turn admiration into direction.",
  "Each morning deals me a new hand.",
  "I applaud my quiet victories.",
  "My story is still raising its hand.",
  "I practice the person I am becoming.",
  "I am the answer I was waiting on.",
  "I affirm it — so it begins.",
];

/* Frame sets are generated by the extraction step — counts must match.
   Phones get square 640px center-crops (frames-m); wide screens get the
   full 1280x720 frames. Chosen once at load. */
const MOBILE =
  matchMedia("(max-width: 720px)").matches ||
  new URLSearchParams(location.search).has("mobile");
const FRAME_DIR = MOBILE ? "frames-m" : "frames";
const CLIPS = Array.from({ length: 12 }, (_, i) => ({
  dir: `${FRAME_DIR}/clip${i + 1}`,
  count: 61,
}));
const DRAW_SCALE = MOBILE ? 0.94 : 0.82;

const N_QUOTES = AFFIRMATIONS.length;
const reducedMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;

/* ---------- theme ---------- */

const themeToggle = document.getElementById("theme-toggle");
const themeLabel = document.getElementById("theme-label");

function isDark() {
  return document.documentElement.dataset.theme === "dark";
}

function applyThemeLabel() {
  /* the button names the theme you would switch TO */
  themeLabel.textContent = isDark() ? "LIGHT" : "DARK";
}

themeToggle.addEventListener("click", () => {
  const next = isDark() ? "light" : "dark";
  document.documentElement.dataset.theme = next;
  localStorage.setItem("affirm-theme", next);
  applyThemeLabel();
  drawnIndex = -1; /* repaint canvas in the new theme */
  requestDraw();
});
applyThemeLabel();

/* ---------- audio: song chapters follow the affirmations ----------
   Web Audio player (fetch → decode → buffer source): reliable everywhere the
   <audio> element is flaky, and gives sample-accurate chapter seeking. */

const soundToggle = document.getElementById("sound-toggle");
const soundLabel = document.getElementById("sound-label");
const SONG_URL = "audio/song.mp3";

const player = {
  ctx: null,
  gain: null,
  buffer: null,
  source: null,
  startedAt: 0, /* ctx.currentTime when offset 0 would have started */
  on: false,
  loading: false,
  healOsc: null,

  /* 528 Hz solfeggio sine blended far beneath the song */
  startHealingTone() {
    if (this.healOsc) return;
    const osc = this.ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.value = 528;
    const g = this.ctx.createGain();
    g.gain.value = 0.012;
    osc.connect(g);
    g.connect(this.ctx.destination);
    osc.start();
    this.healOsc = osc;
  },

  async ensureBuffer() {
    if (this.buffer || this.loading) return;
    this.loading = true;
    try {
      const data = await fetch(SONG_URL).then((r) => r.arrayBuffer());
      this.buffer = await this.ctx.decodeAudioData(data);
    } finally {
      this.loading = false;
    }
  },

  currentTime() {
    if (!this.buffer || !this.source) return 0;
    const t = this.ctx.currentTime - this.startedAt;
    return ((t % this.buffer.duration) + this.buffer.duration) % this.buffer.duration;
  },

  playAt(offset) {
    if (!this.buffer) return;
    if (this.source) {
      try { this.source.stop(); } catch {}
      this.source.disconnect();
    }
    const src = this.ctx.createBufferSource();
    src.buffer = this.buffer;
    src.loop = true;
    src.connect(this.gain);
    /* short fade-in avoids clicks on chapter jumps */
    const now = this.ctx.currentTime;
    this.gain.gain.cancelScheduledValues(now);
    this.gain.gain.setValueAtTime(0.0001, now);
    this.gain.gain.exponentialRampToValueAtTime(1, now + 0.08);
    src.start(0, offset % this.buffer.duration);
    this.source = src;
    this.startedAt = now - offset;
  },
};

window.__affirmPlayer = player; /* debug handle */

function chapterStart(seg) {
  if (!player.buffer) return 0;
  return (player.buffer.duration / N_QUOTES) * seg;
}

function seekToSegment(seg) {
  if (!player.on || !player.buffer) return;
  const start = chapterStart(seg);
  const len = player.buffer.duration / N_QUOTES;
  const t = player.currentTime();
  /* only jump when the playhead has left this affirmation's slice */
  if (t < start - 0.35 || t > start + len + 0.35) {
    player.playAt(start);
  }
}

soundToggle.addEventListener("click", async () => {
  player.on = !player.on;
  soundToggle.setAttribute("aria-pressed", String(player.on));
  soundLabel.textContent = player.on ? "SOUND ON" : "SOUND OFF";
  try {
    if (player.on) {
      if (!player.ctx) {
        player.ctx = new (window.AudioContext || window.webkitAudioContext)();
        player.gain = player.ctx.createGain();
        player.gain.connect(player.ctx.destination);
      }
      const buffering = player.ensureBuffer(); /* don't gate the fetch on resume() */
      await player.ctx.resume();
      await buffering;
      if (player.on) {
        player.startHealingTone();
        player.playAt(chapterStart(Math.max(activeSeg, 0)));
      }
    } else if (player.ctx) {
      await player.ctx.suspend();
    }
  } catch (e) {
    console.warn("Affirm: audio failed —", e.name, e.message);
    player.on = false;
    soundToggle.setAttribute("aria-pressed", "false");
    soundLabel.textContent = "SOUND OFF";
  }
});

/* ---------- clock ---------- */
{
  const timeEl = document.getElementById("clock-time");
  const zoneEl = document.getElementById("clock-zone");
  const tick = () => {
    const d = new Date();
    timeEl.textContent =
      String(d.getHours()).padStart(2, "0") + ":" + String(d.getMinutes()).padStart(2, "0");
    const off = -d.getTimezoneOffset() / 60;
    zoneEl.textContent = "GMT" + (off >= 0 ? "+" : "") + off;
  };
  tick();
  setInterval(tick, 15000);
}

/* ---------- marquee ---------- */
{
  const track = document.getElementById("marquee-track");
  const seq = AFFIRMATIONS.map((a) => `<span class="slash">\\</span>${a}`).join("");
  track.innerHTML = seq + seq; /* doubled for the -50% loop */
}

/* ---------- frame preloading ---------- */

const frames = []; /* flat, global timeline */
const clipOffsets = [];
let totalFrames = 0;
for (const c of CLIPS) {
  clipOffsets.push(totalFrames);
  totalFrames += c.count;
}
frames.length = totalFrames;

let loadedCount = 0;
let firstClipReady = false;
const loaderEl = document.getElementById("scrub-loader");
const loaderPct = document.getElementById("loader-pct");

function frameUrl(clip, i) {
  return `${clip.dir}/f${String(i + 1).padStart(4, "0")}.webp`;
}

function loadClip(ci) {
  const clip = CLIPS[ci];
  const promises = [];
  for (let i = 0; i < clip.count; i++) {
    const gi = clipOffsets[ci] + i;
    promises.push(
      new Promise((res) => {
        const img = new Image();
        img.decoding = "async";
        img.onload = () => {
          frames[gi] = img;
          loadedCount++;
          if (!firstClipReady) {
            loaderPct.textContent = Math.round((loadedCount / CLIPS[0].count) * 100) + "%";
          }
          res();
        };
        img.onerror = res; /* keep last drawn frame on gaps */
        img.src = frameUrl(clip, i);
      })
    );
  }
  return Promise.all(promises);
}

(async () => {
  await loadClip(0);
  firstClipReady = true;
  loaderEl.style.display = "none";
  requestDraw();
  for (let ci = 1; ci < CLIPS.length; ci++) await loadClip(ci);
})();

/* ---------- canvas scrub ---------- */

const canvas = document.getElementById("hands-canvas");
const ctx = canvas.getContext("2d");
const scrubSection = document.querySelector(".scrub");
const quoteEl = document.getElementById("scrub-quote");
const numEl = document.getElementById("scrub-num");
const hintEl = document.getElementById("scrub-hint");

let current = 0; /* smoothed frame position */
let target = 0;
let drawnIndex = -1;
let rafPending = false;

function sizeCanvas() {
  const dpr = Math.min(devicePixelRatio || 1, 2);
  canvas.width = Math.round(canvas.clientWidth * dpr);
  canvas.height = Math.round(canvas.clientHeight * dpr);
  drawnIndex = -1;
  requestDraw();
}
addEventListener("resize", sizeCanvas);

function nearestLoaded(idx) {
  if (frames[idx]) return frames[idx];
  for (let d = 1; d < totalFrames; d++) {
    if (frames[idx - d]) return frames[idx - d];
    if (frames[idx + d]) return frames[idx + d];
  }
  return null;
}

function draw(idx) {
  const img = nearestLoaded(idx);
  if (!img) return;
  const dark = isDark();
  const paperRGB = dark ? "10,10,12" : "245,245,243";
  const cw = canvas.width, ch = canvas.height;
  ctx.filter = "none";
  ctx.fillStyle = `rgb(${paperRGB})`;
  ctx.fillRect(0, 0, cw, ch);
  /* contain-fit scaled down, anchored to the bottom edge — the cuffs stay
     connected to the frame bottom and the hands rise from below */
  const s = Math.min(cw / img.width, ch / img.height) * DRAW_SCALE;
  const w = img.width * s, h = img.height * s;
  const x = (cw - w) / 2, y = ch - h;
  if (dark) ctx.filter = "invert(1)"; /* negative stage: dark paper, dark gloves */
  ctx.drawImage(img, x, y, w, h);
  ctx.filter = "none";

  /* feather the image edges into the paper so the video background never
     reads as a rectangle */
  const F = Math.round(Math.min(w, h) * 0.18);
  const paper = (a) => `rgba(${paperRGB},${a})`;
  let g = ctx.createLinearGradient(0, y, 0, y + F);
  g.addColorStop(0, paper(1)); g.addColorStop(1, paper(0));
  ctx.fillStyle = g; ctx.fillRect(x - 1, y, w + 2, F);
  g = ctx.createLinearGradient(x, 0, x + F, 0);
  g.addColorStop(0, paper(1)); g.addColorStop(1, paper(0));
  ctx.fillStyle = g; ctx.fillRect(x, y - 1, F, h + 2);
  g = ctx.createLinearGradient(x + w, 0, x + w - F, 0);
  g.addColorStop(0, paper(1)); g.addColorStop(1, paper(0));
  ctx.fillStyle = g; ctx.fillRect(x + w - F, y - 1, F, h + 2);

  drawnIndex = idx;
}

/* ---------- quote reveal ---------- */

let activeSeg = -1;

function setSegment(seg) {
  if (seg === activeSeg) return;
  activeSeg = seg;
  numEl.textContent = String(seg + 1).padStart(2, "0");
  quoteEl.innerHTML = AFFIRMATIONS[seg]
    .split(" ")
    .map((w) => `<span class="w">${w}</span>`)
    .join(" ");
  seekToSegment(seg);
}

function updateWords(within) {
  const words = quoteEl.children;
  const n = words.length;
  /* all words revealed by 60% of the segment */
  const shown = Math.floor(Math.min(1, within / 0.6) * n + 0.0001);
  for (let i = 0; i < n; i++) words[i].classList.toggle("on", i < shown);
}

/* ---------- scroll wiring ---------- */

function onScroll() {
  const rect = scrubSection.getBoundingClientRect();
  const runway = rect.height - innerHeight;
  const p = Math.min(1, Math.max(0, -rect.top / runway));
  target = p * (totalFrames - 1);

  const segF = Math.min(0.999999, p) * N_QUOTES;
  const seg = Math.floor(segF);
  setSegment(seg);
  updateWords(segF - seg);

  hintEl.style.opacity = p > 0.005 ? "0" : "1";
  requestDraw();
}
addEventListener("scroll", onScroll, { passive: true });

/* rAF watcher: catches scroll-position changes that don't dispatch a scroll
   event (programmatic jumps, some mobile browsers during momentum) */
let lastY = -1;
(function watchScroll() {
  if (scrollY !== lastY) {
    lastY = scrollY;
    onScroll();
  }
  requestAnimationFrame(watchScroll);
})();

function requestDraw() {
  if (rafPending) return;
  rafPending = true;
  requestAnimationFrame(step);
}

function step() {
  rafPending = false;
  const ease = reducedMotion ? 1 : 0.16;
  current += (target - current) * ease;
  if (Math.abs(target - current) < 0.5) current = target;
  const idx = Math.round(current);
  if (idx !== drawnIndex) draw(idx);
  if (current !== target) requestDraw();
}

/* ---------- statement word reveal ---------- */

for (const el of document.querySelectorAll(".reveal-words")) {
  el.innerHTML = el.textContent
    .trim()
    .split(/\s+/)
    .map((w) => `<span class="w">${w}</span>`)
    .join(" ");
  const words = [...el.children];
  const io = new IntersectionObserver(
    (entries) => {
      if (!entries[0].isIntersecting) return;
      words.forEach((w, i) => setTimeout(() => w.classList.add("on"), reducedMotion ? 0 : i * 28));
      io.disconnect();
    },
    { threshold: 0.4 }
  );
  io.observe(el);
}

/* ---------- boot ---------- */
sizeCanvas();
setSegment(0);
onScroll();
